package cricketrunsapplication;

/**
 * Question 2
 * This class extends CricketScore abstract class and provides
 * concrete implementation of the printRunsScored method
 * 
 * @author Sipho Swartbooi
 */
public class CricketRunsScored extends CricketScore {
    
    // =====================================================================
    // CONSTRUCTOR
    // =====================================================================
    
    /**
     * Constructor for CricketRunsScored class
     * Calls the parent class constructor using super()
     * @param batsmanName The name of the batsman
     * @param stadiumName The name of the stadium
     * @param runsScored The number of runs scored
     */
    public CricketRunsScored(String batsmanName, String stadiumName, int runsScored) {
        // Call the parent class (CricketScore) constructor
        super(batsmanName, stadiumName, runsScored);
    }
    
    // =====================================================================
    // CONCRETE METHOD IMPLEMENTATION
    // =====================================================================
    
    /**
     * Implementation of abstract method from parent class
     * Prints a formatted report of the runs scored
     */
    @Override
    public void printRunsScored() {
        System.out.println("VEHICLE ACCIDENT REPORT");
        System.out.println("***************");
        System.out.println("VEHICLE TYPE: " + getBatsmanName());
        System.out.println("CITY: " + getStadiumName());
        System.out.println("ACCIDENT TOTAL: " + getRunsScored());
        System.out.println("***************");
    }
    
    /**
     * Additional method to demonstrate extended functionality
     * Prints a detailed cricket-specific report
     */
    public void printDetailedReport() {
        System.out.println("\nCRICKET RUNS DETAILED REPORT");
        System.out.println("============================");
        System.out.println("Batsman: " + getBatsmanName());
        System.out.println("Stadium: " + getStadiumName());
        System.out.println("Runs Scored: " + getRunsScored());
        System.out.println("Report Generated by: CricketRunsScored Class");
        System.out.println("============================\n");
    }
}
